# application.yml
spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: sk-92308970955145be843a10878c28ccbf
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3